// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45clr1VbE4flJ_tBvRp0xp8F8WQdl1AM',
    appId: '1:40368658651:web:401ed3053214c6891d14fe',
    messagingSenderId: '40368658651',
    projectId: 'f2h-demo',
    authDomain: 'f2h-demo.firebaseapp.com',
    storageBucket: 'f2h-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9sdEi0GT7LzgkZsnMNGEBIKbhFKjyZFo',
    appId: '1:40368658651:android:1a9f42ab61b559811d14fe',
    messagingSenderId: '40368658651',
    projectId: 'f2h-demo',
    storageBucket: 'f2h-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1HZhHzOuOHLL45X_xZd7iziN-hQDRG6c',
    appId: '1:40368658651:ios:694c119974cab2fd1d14fe',
    messagingSenderId: '40368658651',
    projectId: 'f2h-demo',
    storageBucket: 'f2h-demo.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1HZhHzOuOHLL45X_xZd7iziN-hQDRG6c',
    appId: '1:40368658651:ios:694c119974cab2fd1d14fe',
    messagingSenderId: '40368658651',
    projectId: 'f2h-demo',
    storageBucket: 'f2h-demo.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45clr1VbE4flJ_tBvRp0xp8F8WQdl1AM',
    appId: '1:40368658651:web:3d3d920e56d2cffb1d14fe',
    messagingSenderId: '40368658651',
    projectId: 'f2h-demo',
    authDomain: 'f2h-demo.firebaseapp.com',
    storageBucket: 'f2h-demo.firebasestorage.app',
  );
}
